import { ArrowDownRight, ArrowRight, Check, FileCheck2, Languages, ShieldCheck } from "lucide-react";
import { Link } from "wouter";

const steps = [
  ["01", "Tell your story", "Speak or type in Telugu, Hindi, English, or a mix. Your wording stays visible."],
  ["02", "Confirm what was captured", "Focused questions and deterministic warning guidance make uncertainty explicit."],
  ["03", "Create the handoff", "Edit an evidence-linked draft before choosing what to share with a clinician."],
] as const;

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-[var(--med-bg)] text-[var(--med-foreground)]">
    <nav className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-6 lg:px-8"><Link href="/" className="text-xl font-bold tracking-tight">Med<span className="text-[var(--med-cyan)]">Relay</span></Link><div className="flex items-center gap-3"><span className="hidden text-xs text-[var(--med-muted)] sm:inline">Synthetic demo only</span><Link href="/medrelay" className="rounded-full border border-[var(--med-cyan)]/50 px-4 py-2 text-sm font-semibold text-[var(--med-cyan)] transition hover:bg-[var(--med-cyan)]/10">Open workspace</Link></div></nav>
    <section className="relative mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-14 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:pb-36 lg:pt-24">
      <div className="relative z-10"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[var(--med-teal)]/30 bg-[var(--med-teal)]/10 px-3 py-1.5 text-xs font-semibold uppercase tracking-[.18em] text-[var(--med-teal)]"><span className="h-1.5 w-1.5 rounded-full bg-[var(--med-teal)]" />Patient-to-clinician support</div><h1 className="max-w-4xl text-6xl font-semibold leading-[.98] tracking-[-.06em] sm:text-8xl">Your story,<br /><span className="text-[var(--med-cyan)]">ready for care.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--med-muted)]">MedRelay turns multilingual patient words into a clear, editable handoff draft with traceable evidence. It helps a clinician understand what was said - it never diagnoses or prescribes.</p><div className="mt-9 flex flex-wrap items-center gap-3"><Link href="/medrelay" className="inline-flex items-center gap-2 rounded-xl bg-[var(--med-cyan)] px-5 py-3 font-semibold text-[#041019] transition hover:brightness-110">Start synthetic demo <ArrowRight size={18} /></Link><a href="#how-it-works" className="inline-flex items-center gap-2 rounded-xl border border-white/15 px-5 py-3 text-sm font-semibold text-[var(--med-foreground)] transition hover:border-[var(--med-cyan)]/50"><ArrowDownRight size={17} /> See how it works</a></div><p className="mt-5 text-xs text-[var(--med-muted)]">Not a diagnosis. Not a prescription. Always requires clinician review.</p></div>
      <RelayVisual />
    </section>
    <section id="how-it-works" className="mx-auto max-w-7xl scroll-mt-8 border-t border-white/10 px-5 py-20 lg:px-8"><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[var(--med-cyan)]">A calmer handoff</p><h2 className="mt-4 max-w-md text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Less guessing.<br />More signal.</h2></div><div className="grid gap-3 md:grid-cols-3">{steps.map(([number, title, text]) => <article key={number} className="border-l border-white/15 pl-5"><span className="text-xs font-mono text-[var(--med-cyan)]">{number}</span><h3 className="mt-10 text-lg font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--med-muted)]">{text}</p></article>)}</div></div></section>
    <section className="mx-auto grid max-w-7xl gap-6 px-5 pb-20 lg:grid-cols-2 lg:px-8"><article className="rounded-3xl border border-white/10 bg-[var(--med-surface)] p-7 sm:p-9"><div className="flex items-center gap-3"><Languages className="text-[var(--med-cyan)]" /><h2 className="text-xl font-semibold">Language without a handoff gap</h2></div><p className="mt-4 max-w-xl text-sm leading-7 text-[var(--med-muted)]">Telugu, Hindi, English and mixed-language statements remain patient-authored evidence. Translation or inference is labelled for confirmation instead of being presented as fact.</p><div className="mt-7 flex flex-wrap gap-2 text-xs"><span className="rounded-full border border-white/15 px-3 py-1.5">తెలుగు</span><span className="rounded-full border border-white/15 px-3 py-1.5">हिन्दी</span><span className="rounded-full border border-white/15 px-3 py-1.5">English</span><span className="rounded-full border border-white/15 px-3 py-1.5">Mixed language</span></div></article><article className="rounded-3xl border border-white/10 bg-[var(--med-surface)] p-7 sm:p-9"><div className="flex items-center gap-3"><FileCheck2 className="text-[var(--med-teal)]" /><h2 className="text-xl font-semibold">Evidence you can inspect</h2></div><p className="mt-4 max-w-xl text-sm leading-7 text-[var(--med-muted)]">Each extracted field points back to a patient message. Corrections supersede the current draft while the original wording stays in the audit trail.</p><div className="mt-7 flex items-center gap-2 text-xs text-[var(--med-teal)]"><Check size={15} /> Direct quotes remain visible</div></article></section>
    <section className="mx-auto max-w-7xl px-5 pb-24 lg:px-8"><div className="rounded-3xl border border-amber-300/20 bg-amber-300/[.06] p-7 sm:p-9"><div className="flex items-start gap-4"><ShieldCheck className="mt-1 shrink-0 text-[var(--med-amber)]" /><div><h2 className="text-xl font-semibold">A clear safety boundary</h2><p className="mt-2 max-w-3xl text-sm leading-7 text-[var(--med-muted)]">Deterministic warning screening runs before any provider call. When a warning sign is present, MedRelay gives generic local-emergency-services guidance and stops. It never dispatches help, books care, claims clinical validation, or estimates disease probability.</p></div></div></div></section>
    <section className="mx-auto flex max-w-7xl flex-col items-start gap-5 border-t border-white/10 px-5 py-16 lg:flex-row lg:items-center lg:justify-between lg:px-8"><div><p className="text-3xl font-semibold tracking-[-.04em]">Make the next conversation clearer.</p><p className="mt-2 text-sm text-[var(--med-muted)]">Use synthetic data to explore the full intake-to-handoff flow.</p></div><Link href="/medrelay" className="inline-flex items-center gap-2 rounded-xl bg-[var(--med-cyan)] px-5 py-3 font-semibold text-[#041019]">Start synthetic demo <ArrowRight size={18} /></Link></section>
  </main>;
}

function RelayVisual() {
  return <div className="relay-visual relative min-h-[28rem] overflow-hidden rounded-[2rem] border border-white/10 bg-[var(--med-surface)] p-6 lg:min-h-[34rem]" aria-label="Illustration of patient words becoming an evidence-linked handoff" role="img"><div className="relay-grid absolute inset-0 opacity-60" /><div className="relay-orbit relay-orbit-one" /><div className="relay-orbit relay-orbit-two" /><div className="relative z-10 flex h-full min-h-[25rem] flex-col justify-between"><div className="flex items-center justify-between text-[10px] uppercase tracking-[.22em] text-[var(--med-muted)]"><span>Patient signal</span><span>Draft trace</span></div><div className="relative flex-1"><div className="relay-note relay-note-one"><span className="text-[10px] uppercase tracking-[.16em] text-[var(--med-muted)]">Statement 01</span><p className="mt-2 text-sm leading-6">“I have had a cough since yesterday.”</p></div><div className="relay-line relay-line-one" /><div className="relay-note relay-note-two"><span className="text-[10px] uppercase tracking-[.16em] text-[var(--med-muted)]">Evidence</span><p className="mt-2 text-sm leading-6 text-[var(--med-cyan)]">timeline ← direct quote</p></div><div className="relay-line relay-line-two" /><div className="relay-note relay-note-three"><span className="text-[10px] uppercase tracking-[.16em] text-[var(--med-muted)]">Clinician-review draft</span><p className="mt-2 text-sm leading-6">Missing information highlighted for confirmation.</p></div></div><div className="flex items-center justify-between border-t border-white/10 pt-4 text-xs text-[var(--med-muted)]"><span>Structured, editable, ephemeral</span><span className="text-[var(--med-teal)]">No diagnosis</span></div></div></div>;
}
